---
config:
  riot: /home/cinzia/apache-jena/bin/riot
  jq: /usr/local/jq
  java_vm: -Xmx6096M
annotations:
  gs_output_dir: annotation-files
  downloads:
  - uri: https://www.uniprot.org/uniprot/?query=reviewed%3Ayes%2BAND%2Borganism%3A9606&compress=yes&format=xml
    output_filename: uniprot-{suffix}.xml.gz
    resource: uniprot-uri
  - uri: https://reactome.org/download/current/ReactomePathways.txt
    output_filename: ReactomePathways-{suffix}.txt
    resource: reactome-pathway-data
  - uri: https://reactome.org/download/current/ReactomePathwaysRelation.txt
    output_filename: ReactomePathwaysRelation-{suffix}.txt
    resource: reactome-pathway-relation
  - uri: http://ftp.ebi.ac.uk/pub/databases/genenames/new/json/hgnc_complete_set.json
    output_filename: hgnc_complete_set-{suffix}.json
    resource: hgnc-complete-set
  - uri: http://ftp.ebi.ac.uk/pub/databases/genenames/hcop/human_all_hcop_sixteen_column.txt.gz
    output_filename: human_all_hcop_sixteen_column-{suffix}.txt.gz
    resource: hgnc-orthologs
  - uri: http://www.informatics.jax.org/downloads/reports/HMD_HumanPhenotype.rpt
    output_filename: HMD_HumanPhenotype-{suffix}.rpt
    resource: mouse-phenotypes-orthology
  - uri: http://www.informatics.jax.org/downloads/reports/MGI_PhenoGenoMP.rpt
    output_filename: MGI_PhenoGenoMP-{suffix}.rpt
    resource: mouse-phenotypes-report
  - uri: https://raw.githubusercontent.com/opentargets/expression_hierarchy/master/process/map_with_efos.json
    output_filename: map_with_efos-{suffix}.json
    resource: tissue-translation-map
  - uri: https://raw.githubusercontent.com/opentargets/expression_hierarchy/master/process/curation.tsv
    output_filename: expression_hierarchy_curation-{suffix}.tsv
    resource: tissue-curation-map
  - uri: https://www.proteinatlas.org/download/normal_tissue.tsv.zip
    #This file will saved normal_tissue-{suffix}.tsv
    output_filename: normal_tissue-{suffix}.tsv.zip
    unzip_file: true
    resource: hpa-normal-tissue
  - uri: https://raw.githubusercontent.com/opentargets/data_pipeline/master/mrtarget/resources/eco_scores.tsv
    output_filename: eco_scores-{suffix}.tsv
    resource: eco-scores
annotations_from_buckets:
  gs_output_dir: annotation-files
  downloads:
  - bucket: atlas_baseline_expression/baseline_expression_binned
    output_filename: baseline_expression_binned-{suffix}.tsv
    resource: hpa-rna-level
  - bucket: atlas_baseline_expression/baseline_expression_counts
    output_filename: baseline_expression_counts-{suffix}.tsv
    resource: hpa-rna-value
  - bucket: atlas_baseline_expression/baseline_expression_zscore_binned
    output_filename: baseline_expression_zscore_binned-{suffix}.tsv
    resource: hpa-rna-zscore
  - bucket: otar007-cosmic
    output_filename: cosmic-hallmarks-{suffix}.tsv.gz
    resource: hallmark
    includes: hallmarks
  - bucket: otar001-core/Tractability
    output_filename: tractability_buckets-{suffix}.tsv
    resource: tractability
  - bucket: otar001-core/CancerBiomarkers/annotation
    output_filename: cancerbiomarkers-{suffix}.tsv
    resource: biomarker
  - bucket: otar001-core/ProbeMiner/annotation
    output_filename: chemicalprobes_probeminer-{suffix}.tsv
    resource: chemical-probes-2
  - bucket: otar001-core/AdverseEvents/annotation
    output_filename: adverse-events-{suffix}.csv.gz
    resource: adverse-events
  - bucket: otar001-core/DrugBank/annotation
    output_filename: drugbank-{suffix}.csv.gz
    resource: drugbank
  - bucket: otar001-core/ExperimentalToxicity
    output_filename: experimental-toxicity-{suffix}.tsv
    resource: experimental-toxicity
eco:
  gs_output_dir: annotation-files/ontology
  eco_downloads:
    - uri: https://raw.githubusercontent.com/evidenceontology/evidenceontology/v2021-01-08/eco.owl
      output_filename: ontology-eco-{suffix}.owl
      resource: ontology-eco
      owl_jq: '.["@graph"][]'
    - uri: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/v3.1/releases/so-xp.owl/so.owl
      output_filename: ontology-so-{suffix}.owl
      resource: ontology-so
      owl_jq: '.["@graph"][] | select (.["@type"] == "owl:Class" and .id != null)|.subClassOf=([.subClassOf]|flatten|del(.[]|nulls))|.hasExactSynonym=([.hasExactSynonym]|flatten|del(.[]|nulls))|.hasDbXref=([.hasDbXref]|flatten|del(.[]|nulls))|.inSubset=([.inSubset]|flatten|del(.[]|nulls))|.hasAlternativeId=([.hasAlternativeId]|flatten|del(.[]|nulls))|@json'
efo:
  gs_output_dir: annotation-files/ontology
  hpo_phenotypes:
    uri: http://purl.obolibrary.org/obo/hp/hpoa/phenotype.hpoa
    output_filename: hpo-phenotypes-{suffix}.jsonl
    resource: hpo-phenotype
  disease:
    efo:
      uri: https://github.com/EBISPOT/efo/releases/download/v3.28.0/efo_otar_slim.owl
      output_filename: ontology-efo-v3.28.0.jsonl
      resource: ontology-efo
      owl_jq: '.["@graph"][] | select (.["@type"] == ("Class","Restriction") and ."@id" != null)|.subClassOf=([.subClassOf]|flatten|del(.[]|nulls))|.hasExactSynonym=([.hasExactSynonym]|flatten|del(.[]|nulls))|.hasDbXref=([.hasDbXref]|flatten|del(.[]|nulls))|.inSubset=([.inSubset]|flatten|del(.[]|nulls))|.hasAlternativeId=([.hasAlternativeId]|flatten|del(.[]|nulls))|@json'
      static:
        therapeutic_area: therapeutic_area.txt
        diseases: diseases_efo.jsonl
    hpo:
      uri: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.owl
      output_filename: ontology-hpo.jsonl
      resource: ontology-hpo
      owl_jq: '.["@graph"][] | select (.["@type"] == "owl:Class") | @json'
    mondo:
      uri: https://github.com/monarch-initiative/mondo/releases/download/v2021-04-07/mondo.owl
      output_filename: ontology-mondo.jsonl
      resource: ontology-mondo
      owl_jq: '.["@graph"][] | @json'
chemical_probes:
  output_filename: chemicalprobes_portalprobes-{suffix}.tsv
  resource: chemical-probes-1
  gs_output_dir: annotation-files
  spreadsheets:
  - gkey: 1VL3eHGpvJMaQ7LYp0Kp1plEo-NueP3CT7FUCrW0p2dg
    gid: 1686598114
    output_filename: chemical_probes_SGC.tsv
    cp_type: sgc
  - gkey: 1VL3eHGpvJMaQ7LYp0Kp1plEo-NueP3CT7FUCrW0p2dg
    gid: 1636863333
    output_filename: chemical_probes_portal.tsv
    cp_type: cpp
  - gkey: 1VL3eHGpvJMaQ7LYp0Kp1plEo-NueP3CT7FUCrW0p2dg
    gid: 349856989
    output_filename: open_science_probes.tsv
    cp_type: osp
tep:
  output_filename: tep-{suffix}.json
  resource: tep
  gs_output_dir: annotation-files
  spreadsheets:
  - gkey: 1pV06MTC-szlJRjlgG9rV6WW67r6Nxd9oAXfqZkrNVAU
    gid: 0
    output_filename: tep.tsv
known_target_safety:
  output_filename: known_target_safety-{suffix}.json
  resource: safety
  gs_output_dir: annotation-files
  spreadsheets:
  - gkey: 1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0
    gid: 1760619926
    output_filename: adverse_effects.tsv
    s_type: adr
  - gkey: 1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0
    gid: 650742396
    output_filename: safety_risk_information.tsv
    s_type: sri
  - gkey: 1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0
    gid: 1774810192
    output_filename: UBERON_mapping.tsv
    s_type: ubr
  - gkey: 1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0
    gid: 1717378859
    output_filename: EFO_mapping.tsv
    s_type: efo
  - gkey: 1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0
    gid: 1223815020
    output_filename: references.tsv
    s_type: ref
ensembl:
  ensembl_release: homo_sapiens_core_104_38
  extension_file: _genes.json.gz
  resource: ensembl-filename
  gs_output_dir: annotation-files
drug:
  gs_output_dir: annotation-files/chembl
  datasources:
    chembl:
      type: elasticsearch
      url: hh-rke-wp-webadmin-04-worker-4.caas.ebi.ac.uk
      port: 32000
      indices:
        chembl-indication:
          name: chembl_28_drug_indication
          fields:
            - '_metadata'
            - 'molecule_chembl_id'
            - 'efo_id'
            - 'max_phase_for_ind'
            - 'indication_refs'
        chembl-mechanism:
          name: chembl_28_mechanism
          fields:
            - 'molecule_chembl_id'
            - 'target_chembl_id'
            - 'action_type'
            - 'mechanism_of_action'
            - 'mechanism_refs'
            - 'record_id'
            - 'parent_molecule_chembl_id'
            - '_metadata'
        chembl-molecule:
          name: chembl_28_molecule
          fields:
            - 'molecule_chembl_id'
            - 'molecule_hierarchy'
            - 'molecule_type'
            - 'pref_name'
            - 'first_approval'
            - 'max_phase'
            - 'withdrawn_flag'
            - 'withdrawn_reason'
            - 'withdrawn_year'
            - 'withdrawn_country'
            - 'withdrawn_class'
            - 'black_box_warning'
            - 'molecule_synonyms'
            - 'cross_references'
            - 'chebi_par_id'
            - 'molecule_structures'
        chembl-target:
          name: chembl_28_target
          fields:
            - 'target_chembl_id'
            - 'target_components'
            - 'target_type'
            - 'pref_name'
        chembl-drug-warning:
          name: chembl_28_drug_warning
          fields:
            - '_metadata'
            - 'molecule_chembl_id'
            - 'parent_molecule_chembl_id'
            - 'warning_class'
            - 'warning_country'
            - 'warning_description'
            - 'warning_id'
            - 'warning_refs'
            - 'warning_type'
            - 'warning_year'
interactions:
  gs_output_dir: annotation-files/interactions
  intact_info:
    uri : ftp://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current/data/interactor_pair_interactions.json
    output_filename: intact-interactors-{suffix}.json
    resource: intact
  rna_central:
    uri: ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/ensembl.tsv
    output_filename: rna_central_ensembl.tsv
    output_dir: rna-central
    resource: rna-central-interaction
  uniprot_info:
    uri : ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping.dat.gz
    output_filename: HUMAN_9606_idmapping.dat.gz
    output_dir: human-mapping
    resource: uniprot-interaction
  string_info:
    uri: https://stringdb-static.org/download/protein.links.detailed.v11.0/9606.protein.links.detailed.v11.0.txt.gz
    output_filename: string-interactions.json.gz
    output_string: string-interactions-{suffix}.json.gz
    resource: string-interaction
    score_threshold: 0
    score_limit:
    additional_resouces:
      ensembl_ftp:
        uri: http://ftp.ensembl.org/pub/current_gtf/homo_sapiens/Homo_sapiens.GRCh38.104.chr.gtf.gz
        output_filename: Homo_sapiens.GRCh38.chr.gtf.gz
        output_protein_mapping: ensembl-protein-{suffix}.json.gz
        resource: string-interaction-ensembl-protein
      network_json_schema:
        url: https://raw.githubusercontent.com/opentargets/json_schema/master/OT_network_schema.json
evidences:
  gs_output_dir: evidence-files
  downloads:
  - bucket: otar000-evidence_input/Orphanet/json
    output_filename: orphanet-{suffix}.json.gz
    output_spark_dir: orphanet-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/ClinGen/json
    output_filename: clingen-{suffix}.json.gz
    output_spark_dir: clingen-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/CRISPR/json
    output_filename: crispr-{suffix}.json.gz
    output_spark_dir: crispr-{suffix}
    resource: input-file
  - bucket: otar006-reactome
    output_filename: reactome-{suffix}.json.gz
    output_spark_dir: reactome-{suffix}
    resource: input-file
  - bucket: otar007-cosmic
    output_filename: cosmic-{suffix}.json.gz
    output_spark_dir: cosmic-{suffix}
    excludes: hallmarks
    resource: input-file
  - bucket: otar008-chembl
    output_filename: chembl-{suffix}.json.gz
    output_spark_dir: chembl-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/Genetics_portal/json/
    output_filename: genetics-portal-evidences-{suffix}.json.gz
    output_spark_dir: genetics-portal-evidences-{suffix}
    resource: input-file
  - bucket: otar010-atlas
    output_filename: atlas-{suffix}.json.gz
    output_spark_dir: atlas-{suffix}
    resource: input-file
  - bucket: otar011-uniprot
    output_filename: uniprot-{suffix}.json.gz
    output_spark_dir: uniprot-{suffix}
    resource: input-file
  - bucket: otar012-eva
    output_filename: eva-{suffix}.json.gz
    output_spark_dir: eva-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/EPMC/json
    output_filename: epmc-{suffix}.json.gz
    output_spark_dir: epmc-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/Gene2Phenotype/json
    output_filename: gene2phenotype-{suffix}.json.gz
    output_spark_dir: gene2phenotype-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/GenomicsEngland/json
    output_filename: genomics_england-{suffix}.json.gz
    output_spark_dir: genomics-england-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/IntOgen/json
    output_filename: intogen-{suffix}.json.gz
    output_spark_dir: intogen-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/PhenoDigm/json
    output_filename: phenodigm-{suffix}.json.gz
    output_spark_dir: phenodigm-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/PheWAS/json
    output_filename: phewas_catalog-{suffix}.json.gz
    output_spark_dir: phewas-catalog-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/PROGENy/json
    output_filename: progeny-{suffix}.json.gz
    output_spark_dir: progeny-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/SLAPEnrich/json
    output_filename: slapenrich-{suffix}.json.gz
    output_spark_dir: slapenrich-{suffix}
    resource: input-file
  - bucket: otar000-evidence_input/SysBio/json
    output_filename: sysbio-{suffix}.json.gz
    output_spark_dir: sysbio-{suffix}
    resource: input-file
#The uri of data_pipeline_schema should point to the latest config data file.
data_pipeline_schema:
  uri: https://storage.googleapis.com/open-targets-data-releases/21.02/templates/template.mrtarget.data.21.02.yml
  output_filename: mrtarget.data.yml
