---
config:
  gsutil : /snap/bin/gsutil
  riot: /usr/share/apache-jena/bin/riot
  jq: /usr/bin/jq
  java_vm: -Xmx6096M
disease:
  etl:
   hpo_phenotypes:
    uri: http://purl.obolibrary.org/obo/hp/hpoa/phenotype.hpoa
    output_filename: hpo-phenotypes-{suffix}.jsonl
    path: ontology-inputs
   efo:
    uri: https://github.com/EBISPOT/efo/releases/download/v3.38.0/efo_otar_slim.owl
    output_filename: ontology-efo-v3.38.0.jsonl
    path: ontology-inputs
    owl_jq: '.["@graph"][] | select (.["@type"] == ("Class","Restriction") and ."@id" != null)|.subClassOf=([.subClassOf]|flatten|del(.[]|nulls))|.hasExactSynonym=([.hasExactSynonym]|flatten|del(.[]|nulls))|.hasDbXref=([.hasDbXref]|flatten|del(.[]|nulls))|.inSubset=([.inSubset]|flatten|del(.[]|nulls))|.hasAlternativeId=([.hasAlternativeId]|flatten|del(.[]|nulls))|@json'
    diseases_static_file: diseases_efo.jsonl
   hpo:
    uri: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2021-10-10/hp.owl
    output_filename: ontology-hpo.jsonl
    path: ontology-inputs
    owl_jq: '.["@graph"][] | select (.["@type"] == "owl:Class") | @json'
   mondo:
    uri: https://github.com/monarch-initiative/mondo/releases/download/v2021-12-30/mondo.owl
    output_filename: ontology-mondo.jsonl
    path: ontology-inputs
    owl_jq: '.["@graph"][] | @json'
  miniset: yes
drug:
  http_downloads:
   - uri: https://go.drugbank.com/releases/5-1-9/downloads/all-drugbank-vocabulary
     path: chembl-inputs
     output_filename: 'drugbank_vocabulary.csv'
  gs_downloads_latest:
   - bucket: otar001-core/DrugBank/annotation
     output_filename: drugbank-{suffix}.csv.gz
     path: chembl-inputs
  etl:
    chembl:
      type: elasticsearch
      url: hh-rke-wp-webadmin-04-worker-4.caas.ebi.ac.uk
      port: 32000
      path: chembl-inputs
      indices:
        chembl-indication:
          name: chembl_29_drug_indication
          fields:
            - '_metadata'
            - 'molecule_chembl_id'
            - 'efo_id'
            - 'max_phase_for_ind'
            - 'indication_refs'
        chembl-mechanism:
          name: chembl_29_mechanism
          fields:
            - 'molecule_chembl_id'
            - 'target_chembl_id'
            - 'action_type'
            - 'mechanism_of_action'
            - 'mechanism_refs'
            - 'record_id'
            - 'parent_molecule_chembl_id'
            - '_metadata'
        chembl-molecule:
          name: chembl_29_molecule
          fields:
            - 'molecule_chembl_id'
            - 'molecule_hierarchy'
            - 'molecule_type'
            - 'pref_name'
            - 'first_approval'
            - 'max_phase'
            - 'withdrawn_flag'
            - 'withdrawn_reason'
            - 'withdrawn_year'
            - 'withdrawn_country'
            - 'withdrawn_class'
            - 'black_box_warning'
            - 'molecule_synonyms'
            - 'cross_references'
            - 'chebi_par_id'
            - 'molecule_structures'
        chembl-target:
          name: chembl_29_target
          fields:
            - '_metadata'
            - 'target_chembl_id'
            - 'target_components'
            - 'target_type'
            - 'pref_name'
        chembl-drug-warning:
          name: chembl_29_drug_warning
          fields:
            - '_metadata'
            - 'molecule_chembl_id'
            - 'parent_molecule_chembl_id'
            - 'warning_class'
            - 'warning_country'
            - 'warning_description'
            - 'warning_id'
            - 'warning_refs'
            - 'warning_type'
            - 'warning_year'
  miniset: yes
evidence:
  gs_downloads_latest:
  - bucket: otar000-evidence_input/CancerBiomarkers/json
    output_filename: cancerbiomarkers-{suffix}.json.gz
    output_spark_dir: cancerbiomarkers-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/Orphanet/json
    output_filename: orphanet-{suffix}.json.gz
    output_spark_dir: orphanet-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/ClinGen/json
    output_filename: clingen-{suffix}.json.gz
    output_spark_dir: clingen-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/CRISPR/json
    output_filename: crispr-{suffix}.json.gz
    output_spark_dir: crispr-{suffix}
    path: evidence-files
  - bucket: otar006-reactome
    output_filename: reactome-{suffix}.json.gz
    output_spark_dir: reactome-{suffix}
    path: evidence-files
  - bucket: otar007-cosmic
    output_filename: cosmic-{suffix}.json.gz
    output_spark_dir: cosmic-{suffix}
    excludes: hallmarks
    path: evidence-files
  - bucket: otar008-chembl
    output_filename: chembl-{suffix}.json.gz
    output_spark_dir: chembl-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/Genetics_portal/json/
    output_filename: genetics-portal-evidences-{suffix}.json.gz
    output_spark_dir: genetics-portal-evidences-{suffix}
    path: evidence-files
  - bucket: otar010-atlas
    output_filename: atlas-{suffix}.json.gz
    output_spark_dir: atlas-{suffix}
    path: evidence-files
  - bucket: otar011-uniprot
    output_filename: uniprot-{suffix}.json.gz
    output_spark_dir: uniprot-{suffix}
    path: evidence-files
  - bucket: otar012-eva
    output_filename: eva-{suffix}.json.gz
    output_spark_dir: eva-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/EPMC/json
    output_filename: epmc-{suffix}.json.gz
    output_spark_dir: epmc-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/Gene2Phenotype/json
    output_filename: gene2phenotype-{suffix}.json.gz
    output_spark_dir: gene2phenotype-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/GenomicsEngland/json
    output_filename: genomics_england-{suffix}.json.gz
    output_spark_dir: genomics-england-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/IntOgen/json
    output_filename: intogen-{suffix}.json.gz
    output_spark_dir: intogen-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/PhenoDigm/json
    output_filename: phenodigm-{suffix}.json.gz
    output_spark_dir: phenodigm-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/PheWAS/json
    output_filename: phewas_catalog-{suffix}.json.gz
    output_spark_dir: phewas-catalog-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/PROGENy/json
    output_filename: progeny-{suffix}.json.gz
    output_spark_dir: progeny-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/SLAPEnrich/json
    output_filename: slapenrich-{suffix}.json.gz
    output_spark_dir: slapenrich-{suffix}
    path: evidence-files
  - bucket: otar000-evidence_input/SysBio/json
    output_filename: sysbio-{suffix}.json.gz
    output_spark_dir: sysbio-{suffix}
    path: evidence-files
expression:
  http_downloads:
  - uri: https://raw.githubusercontent.com/opentargets/expression_hierarchy/master/process/curation.tsv
    output_filename: expression_hierarchy_curation-{suffix}.tsv
    path: expression-inputs
  gs_downloads_latest:
  - bucket: atlas_baseline_expression/baseline_expression_binned
    output_filename: baseline_expression_binned-{suffix}.tsv
    path: expression-inputs
  - bucket: atlas_baseline_expression/baseline_expression_counts
    output_filename: baseline_expression_counts-{suffix}.tsv
    path: expression-inputs
  - bucket: atlas_baseline_expression/baseline_expression_zscore_binned
    output_filename: baseline_expression_zscore_binned-{suffix}.tsv
    path: expression-inputs
  etl:
    tissue_translation_map:
      uri: https://raw.githubusercontent.com/opentargets/expression_hierarchy/master/process/map_with_efos.json
      output_filename: tissue-translation-map-{suffix}.json
      path: expression-inputs
    normal_tissues:
      uri: https://www.proteinatlas.org/download/normal_tissue.tsv.zip
      output_filename: normal_tissue-{suffix}.tsv.gz
      path: expression-inputs
go:
  http_downloads:
  - uri: http://purl.obolibrary.org/obo/go.obo
    output_filename: go.obo
    path: gene-ontology-inputs
homologues:
  uri: ftp://ftp.ensembl.org/pub/release-{release}/json/
  path: target-inputs/homologue
  release: 105
  jq: ".genes[] | [.id, .name] | @tsv"
  resources:
      - 'caenorhabditis_elegans'
      - 'canis_lupus_familiaris'
      - 'cavia_porcellus'
      - 'danio_rerio'
      - 'drosophila_melanogaster'
      - 'macaca_mulatta'
      - 'mus_musculus'
      - 'oryctolagus_cuniculus'
      - 'pan_troglodytes'
      - 'rattus_norvegicus'
      - 'sus_scrofa'
      - 'sus_scrofa_usmarc'
      - 'xenopus_tropicalis'
      - 'homo_sapiens'
interactions:
  ftp_downloads:
  - uri: ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/ensembl.tsv
    output_filename: rna_central_ensembl.tsv
    path: interactions-inputs
  - uri : ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping.dat.gz
    output_filename: HUMAN_9606_idmapping.dat.gz
    path: interactions-inputs
  - uri : ftp://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current/data/interactor_pair_interactions.json
    output_filename: intact-interactors-{suffix}.json
    path: interactions-inputs
  http_downloads:
  - uri: https://stringdb-static.org/download/protein.links.detailed.v11.5/9606.protein.links.detailed.v11.0.txt.gz
    output_filename: string-interactions-{suffix}.json.gz
    path: interactions-inputs
  - uri: http://ftp.ensembl.org/pub/current_gtf/homo_sapiens/Homo_sapiens.GRCh38.105.chr.gtf.gz
    output_filename: Homo_sapiens.GRCh38.chr.gtf.gz
    path: interactions-inputs
mousephenotypes:
  gs_downloads_latest:
  - bucket: otar001-core/MousePhenotypes
    output_filename: mousePhenotypes-{suffix}.json.gz
    path: mouse-phenotypes-inputs
openfda:
  http_downloads:
    - uri: 'https://raw.githubusercontent.com/opentargets/platform-etl-backend/master/src/main/resources/blacklisted_events.txt'
      path: fda-inputs
      output_filename: 'blacklisted_events.txt'
  etl:
    downloads:
      uri: 'https://api.fda.gov/download.json'
      path: fda-inputs
      output_filename: 'openfda_file_listing.json'
reactome:
  http_downloads:
  - uri: https://reactome.org/download/current/ReactomePathways.txt
    output_filename: ReactomePathways-{suffix}.txt
    path: reactome-inputs
  - uri: https://reactome.org/download/current/ReactomePathwaysRelation.txt
    output_filename: ReactomePathwaysRelation-{suffix}.txt
    path: reactome-inputs
so:
  etl:
    uri: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/v3.1/releases/so-xp.owl/so.owl
    output_filename: ontology-so-{suffix}.json
    path: so-inputs
    owl_jq: '.["@graph"][] | select (.["@type"] == "owl:Class" and .id != null)|.subClassOf=([.subClassOf]|flatten|del(.[]|nulls))|.hasExactSynonym=([.hasExactSynonym]|flatten|del(.[]|nulls))|.hasDbXref=([.hasDbXref]|flatten|del(.[]|nulls))|.inSubset=([.inSubset]|flatten|del(.[]|nulls))|.hasAlternativeId=([.hasAlternativeId]|flatten|del(.[]|nulls))|@json'
target:
  http_downloads:
  - uri: http://ftp.ebi.ac.uk/pub/databases/genenames/new/json/hgnc_complete_set.json
    output_filename: hgnc_complete_set-{suffix}.json
    path: target-inputs/genenames
  - uri: https://reactome.org/download/current/Ensembl2Reactome.txt
    output_filename: Ensembl2Reactome.txt
    path: target-inputs/reactome
  - uri: http://ftp.ebi.ac.uk/pub/databases/genenames/hcop/human_all_hcop_sixteen_column.txt.gz
    output_filename: human_all_hcop_sixteen_column-{suffix}.txt.gz
    path: target-inputs/genenames
  - uri: https://cog.sanger.ac.uk/cmp/download/gene_identifiers_latest.csv.gz
    output_filename: gene_identifiers_latest.csv.gz
    path: target-inputs/project-scores
  - uri: https://www.uniprot.org/uniprot/?query=reviewed%3Ayes%2BAND%2Borganism%3A9606&compress=yes&format=txt
    output_filename: uniprot-{suffix}.txt.gz
    path: target-inputs/uniprot
  - uri: https://www.uniprot.org/locations/?query=*&format=tab&force=true&columns=id&compress=yes
    output_filename: uniprot-ssl-{suffix}.tsv.gz
    path: target-inputs/uniprot
  gs_downloads_latest:
  - bucket: otar001-core/subcellularLocations
    output_filename: subcellular_locations_ssl-{suffix}.tsv
    path: target-inputs/hpa
  - bucket: otar007-cosmic
    output_filename: cosmic-hallmarks-{suffix}.tsv.gz
    path: target-inputs/hallmarks
    includes: hallmarks
  - bucket: otar001-core/TEPs/data_files
    output_filename: tep-{suffix}.json.gz
    path: target-inputs/tep
  - bucket: otar001-core/ChemicalProbes/annotation
    output_filename: chemicalprobes-{suffix}.json
    path: target-inputs/chemicalprobes
  - bucket: otar001-core/TargetSafety/data_files/adverse_events
    output_filename: adverse_event_safety-{suffix}.json
    path: target-inputs/safety/adverse_events
  - bucket: otar001-core/TargetSafety/data_files/safety_risk/
    output_filename: sr-{suffix}.json
    path: target-inputs/safety/safety_risk
  - bucket: otar001-core/TargetSafety/data_files/toxcast/
    output_filename: ToxCast-{suffix}.tsv
    path: target-inputs/safety/toxcast
  - bucket: otar001-core/Tractability
    output_filename: tractability-{suffix}.tsv
    path: target-inputs/tractability
  ftp_downloads:
  - uri: ftp://ftp.ensembl.org/pub/release-105/tsv/ensembl-compara/homologies/homo_sapiens/Compara.105.protein_default.homologies.tsv.gz
    output_filename: cpd.tsv.gz
    path: target-inputs/homologue
  - uri: ftp://ftp.ensembl.org/pub/release-105/tsv/ensembl-compara/homologies/homo_sapiens/Compara.105.ncrna_default.homologies.tsv.gz
    output_filename: crna.tsv.gz
    path: target-inputs/homologue
  - uri: ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/ensembl.tsv
    output_filename: ensembl.tsv
    path: target-inputs/go
  - uri: ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gaf.gz
    output_filename: goa_human.gaf.gz
    path: target-inputs/go
  - uri: ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_rna.gaf.gz
    output_filename: goa_human_rna.gaf.gz
    path: target-inputs/go
  - uri: ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gpa.gz
    output_filename: goa_human_eco.gpa.gz
    path: target-inputs/go
  - uri: ftp://ftp.ensembl.org/pub/release-105/species_EnsemblVertebrates.txt
    output_filename: species_EnsemblVertebrates.txt
    path: target-inputs/homologue
  - uri: ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz
    output_filename: Homo_sapiens.gene_info.gz
    path: target-inputs/ncbi
  etl:
    gnomad:
      uri: https://storage.googleapis.com/gcp-public-data--gnomad/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz
      output_filename: gnomad_lof_by_gene.txt.gz
      path: target-inputs/gnomad
    subcellular_location:
      uri: https://www.proteinatlas.org/download/subcellular_location.tsv.zip
      output_filename: subcellular_location.tsv.gz
      path: target-inputs/hpa
    project_scores:
      uri: https://cog.sanger.ac.uk/cmp/download/essentiality_matrices.zip
      output_filename: essentiality_matrices.zip
      path: target-inputs/project-scores
    ensembl:
      release: 105
      uri: ftp://ftp.ensembl.org/pub/release-{release}/json/homo_sapiens/homo_sapiens.json
      output_filename: homo_sapiens.jsonl
      path: target-inputs/ensembl
      jq: '.genes[] | {id: .id, biotype: .biotype, description: .description, end: .end, start: .start, strand: .strand, chromosome: .seq_region_name, approvedSymbol: .name, transcripts: .transcripts, signalP: .SignalP, uniprot_trembl: ."Uniprot/SPTREMBL", uniprot_swissprot: ."Uniprot/SWISSPROT"}'
  miniset: yes