---
config:
  output_path: ./output
  gcp_credentials_path: ./credentials/gcs_credentials.json
  gcp_bucket_path: gs://open-targets-pre-data-releases/24.06dev-test
  log_level: DEBUG

steps:
  go:
    - name: download
      source: http://purl.obolibrary.org/obo/go.obo
      destination: gene-ontology-inputs/go.obo

  baselineexpression:
    - name: download-latest
      source: gs://otar000-evidence_input/BaselineExpression/json
      destination: expression-inputs/baseline_expression.json.gz
