---
config:
  output_path: ./output
  gcp_credentials_path: ./credentials/gcs_credentials.json
  gcp_bucket_path: gs://open-targets-pre-data-releases/24.06dev-test
  log_level: DEBUG

scratch_pad:
  efo_release_version: v3.65.0
  ensembl_release_version: '111'
  chembl_release_version: '34'

steps:
  baseline_expression:
    - name: download_latest baseline_expression
      source: gs://otar000-evidence_input/BaselineExpression/json
      destination: expression-inputs/baseline_expression.json.gz

  evidence:
    - name: download_latest cancerbiomarkers
      source: gs://otar000-evidence_input/CancerBiomarkers/json
      destination: evidence-files/cancerbiomarkers.json.gz
    - name: download_latest chembl
      source: gs://otar000-evidence_input/ChEMBL/json
      destination: evidence-files/chembl.json.gz
    - name: download_latest clingen
      source: gs://otar000-evidence_input/ClinGen/json
      destination: evidence-files/clingen.json.gz
    - name: download_latest crispr
      source: gs://otar000-evidence_input/CRISPR/json
      destination: evidence-files/crispr.json.gz
    - name: download_latest crispr_screen
      source: gs://otar000-evidence_input/Crispr_screens/json
      destination: evidence-files/crispr_screen.json.gz
    - name: download_latest gene2phenotype
      source: gs://otar000-evidence_input/Gene2Phenotype/json
      destination: evidence-files/gene2phenotype.json.gz
    - name: download_latest gene_burden
      source: gs://otar000-evidence_input/GeneBurden/json
      destination: evidence-files/gene_burden.json.gz
    - name: download_latest evidences
      source: gs://otar000-evidence_input/Genetics_portal/json
      destination: evidence-files/genetics-portal-evidences.json.gz
    - name: download_latest genomics_england
      source: gs://otar000-evidence_input/GenomicsEngland/json
      destination: evidence-files/genomics_england.json.gz
    - name: download_latest impc
      source: gs://otar000-evidence_input/IMPC/json
      destination: evidence-files/impc.json.gz
    - name: download_latest intogen
      source: gs://otar000-evidence_input/IntOgen/json
      destination: evidence-files/intogen.json.gz
    - name: download_latest orphanet
      source: gs://otar000-evidence_input/Orphanet/json
      destination: evidence-files/orphanet.json.gz
    - name: download_latest progeny
      source: gs://otar000-evidence_input/PROGENy/json
      destination: evidence-files/progeny.json.gz
    - name: download_latest slapenrich
      source: gs://otar000-evidence_input/SLAPEnrich/json
      destination: evidence-files/slapenrich.json.gz
    - name: download_latest sysbio
      source: gs://otar000-evidence_input/SysBio/json
      destination: evidence-files/sysbio.json.gz
    - name: download_latest reactome
      source: gs://otar006-reactome
      destination: evidence-files/reactome.json.gz
    - name: get_file_list cosmic
      source: gs://otar007-cosmic
      pattern: '!hallmarks'
      scratch_pad_key: cosmic_file_list
    - name: download_latest cosmic
      source: ${cosmic_file_list}
      destination: evidence-files/cosmic.json.gz
    - name: download_latest atlas.
      source: gs://otar010-atlas
      destination: evidence-files/atlas.json.bz2
    - name: download_latest uniprot
      source: gs://otar011-uniprot
      destination: evidence-files/uniprot.json.gz
    - name: download_latest eva
      source: gs://otar012-eva/disease-target-evidence
      destination: evidence-files/eva.json.gz

  go:
    - name: download gene-ontology
      source: http://purl.obolibrary.org/obo/go.obo
      destination: gene-ontology-inputs/go.obo

  homologues:
    # - name: scratch_pad
    #   key: species
    #   value:
    #     - caenorhabditis_elegans
    #     - canis_lupus_familiaris
    #     - cavia_porcellus
    #     - danio_rerio
    #     - drosophila_melanogaster
    #     - macaca_mulatta
    #     - mus_musculus
    #     - oryctolagus_cuniculusiter
    #     - pan_troglodytes
    #     - rattus_norvegicus
    #     - sus_scrofa
    #     - xenopus_tropicalis
    #     - homo_sapiens

    # - name: generate
    #   generate: download
    #   source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/${species}/${species}.json
    #   destination: target-inputs/homologue/gene_dictionary/${species}.json
    # - name: generate
    #   generate: download
    #   source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/${species}/${species}.json
    #   destination: target-inputs/homologue/gene_dictionary/${species}.json
    # - name: generate
    #   generate: download
    #   source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/${species}/${species}.json
    #   destination: target-inputs/homologue/gene_dictionary/${species}.json


      # caenorhabditis_elegans
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/caenorhabditis_elegans/caenorhabditis_elegans.json
      destination: target-inputs/homologue/gene_dictionary/caenorhabditis_elegans.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/caenorhabditis_elegans/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/caenorhabditis_elegans.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/caenorhabditis_elegans/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/caenorhabditis_elegans.tsv.gz

      # canis_lupus_familiaris
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/canis_lupus_familiaris/canis_lupus_familiaris.json
      destination: target-inputs/homologue/gene_dictionary/canis_lupus_familiaris.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/canis_lupus_familiaris/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/canis_lupus_familiaris.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/canis_lupus_familiaris/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/canis_lupus_familiaris.tsv.gz

      # cavia_porcellus
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/cavia_porcellus/cavia_porcellus.json
      destination: target-inputs/homologue/gene_dictionary/cavia_porcellus.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/cavia_porcellus/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/cavia_porcellus.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/cavia_porcellus/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/cavia_porcellus.tsv.gz

      # danio_rerio
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/danio_rerio/danio_rerio.json
      destination: target-inputs/homologue/gene_dictionary/danio_rerio.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/danio_rerio/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/danio_rerio.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/danio_rerio/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/danio_rerio.tsv.gz

      # drosophila_melanogaster
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/drosophila_melanogaster/drosophila_melanogaster.json
      destination: target-inputs/homologue/gene_dictionary/drosophila_melanogaster.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/drosophila_melanogaster/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/drosophila_melanogaster.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/drosophila_melanogaster/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/drosophila_melanogaster.tsv.gz

      # macaca_mulatta
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/macaca_mulatta/macaca_mulatta.json
      destination: target-inputs/homologue/gene_dictionary/macaca_mulatta.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/macaca_mulatta/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/macaca_mulatta.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/macaca_mulatta/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/macaca_mulatta.tsv.gz

      # mus_musculus
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/mus_musculus/mus_musculus.json
      destination: target-inputs/homologue/gene_dictionary/mus_musculus.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/mus_musculus/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/mus_musculus.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/mus_musculus/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/mus_musculus.tsv.gz

      # oryctolagus_cuniculus
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/oryctolagus_cuniculus/oryctolagus_cuniculus.json
      destination: target-inputs/homologue/gene_dictionary/oryctolagus_cuniculus.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/oryctolagus_cuniculus/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/oryctolagus_cuniculus.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/oryctolagus_cuniculus/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/oryctolagus_cuniculus.tsv.gz

      # pan_troglodytes
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/pan_troglodytes/pan_troglodytes.json
      destination: target-inputs/homologue/gene_dictionary/pan_troglodytes.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/pan_troglodytes/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/pan_troglodytes.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/pan_troglodytes/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/pan_troglodytes.tsv.gz

      # rattus_norvegicus
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/rattus_norvegicus/rattus_norvegicus.json
      destination: target-inputs/homologue/gene_dictionary/rattus_norvegicus.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/rattus_norvegicus/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/rattus_norvegicus.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/rattus_norvegicus/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/rattus_norvegicus.tsv.gz

      # sus_scrofa
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/sus_scrofa/sus_scrofa.json
      destination: target-inputs/homologue/gene_dictionary/sus_scrofa.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/sus_scrofa/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/sus_scrofa.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/sus_scrofa/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/sus_scrofa.tsv.gz

      # xenopus_tropicalis
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/xenopus_tropicalis/xenopus_tropicalis.json
      destination: target-inputs/homologue/gene_dictionary/xenopus_tropicalis.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/xenopus_tropicalis/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/xenopus_tropicalis.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/xenopus_tropicalis/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/xenopus_tropicalis.tsv.gz

      # homo_sapiens
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/json/homo_sapiens/homo_sapiens.json
      destination: target-inputs/homologue/gene_dictionary/homo_sapiens.json
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/homo_sapiens/Compara.${ensembl_release_version}.ncrna_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/homo_sapiens.tsv.gz
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/tsv/ensembl-compara/homologies/homo_sapiens/Compara.${ensembl_release_version}.protein_default.homologies.tsv.gz
      destination: target-inputs/homologue/homologies/homo_sapiens.tsv.gz

  interactions:
    - name: download
      source: https://ftp.ensembl.org/pub/release-${ensembl_release_version}/gtf/homo_sapiens/Homo_sapiens.GRCh38.${ensembl_release_version}.chr.gtf.gz
      destination: interactions-inputs/Homo_sapiens.GRCh38.chr.gtf.gz
    - name: download
      source: https://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/ensembl.tsv
      destination: interactions-inputs/rna_central_ensembl.tsv
    - name: download
      source: https://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping.dat.gz
      destination: interactions-inputs/HUMAN_9606_idmapping.dat.gz
    - name: download
      source: https://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current/data/interactor_pair_interactions.json
      destination: interactions-inputs/intact-interactors.json
    - name: download_latest
      source: otar001-core/stringInteractions
      destination: interactions-inputs/string-interactions.txt.gz

  literature:
    - name: download
      source: https://ftp.ebi.ac.uk/pub/databases/pmc/DOI/PMID_PMCID_DOI.csv.gz
      destination: literature-inputs/PMID_PMCID_DOI.csv.gz

  mouse_phenotypes:
    - name: download_latest
      source: otar001-core/MousePhenotypes
      destination: mouse-phenotypes-inputs/mouse_phenotypes.json.gz

  otar:
    - name: download
      source: https://docs.google.com/spreadsheets/d/1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs/export?format=csv&gid=1179867447
      destination: otar-inputs/otar_meta.csv
    - name: download
      source: https://docs.google.com/spreadsheets/d/1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs/export?format=csv&gid=72910172
      destination: otar-inputs/otar_project_to_efo.csv

  pharmacogenomics:
    - name: download_latest
      source: otar012-eva/pharmacogenomics
      destination: pharmacogenomics-inputs/pharmacogenomics.json.gz

  ppp_evidence:
    - name: download_latest
      source: otar013-ppp/validation_lab
      destination: evidence-files/validation_lab.json.gz
    - name: download_latest
      source: otar013-ppp/encore
      destination: evidence-files/encore.json.gz
    - name: download_latest
      source: otar013-ppp/ot_crispr
      destination: evidence-files/ot_crispr.json.gz

  reactome:
    - name: download
      source: https://reactome.org/download/current/ReactomePathways.txt
      destination: reactome-inputs/ReactomePathways.txt
    - name: download
      source: https://reactome.org/download/current/ReactomePathwaysRelation.txt
      destination: reactome-inputs/ReactomePathwaysRelation.txt

  so:
    - name: download
      source: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/Ontology_Files/so.json
      destination: so-inputs/so.json

  target_engine:
    - name: download
      source: https://www.proteinatlas.org/download/proteinatlas.json.gz
      destination: targetEngine-inputs/proteinatlas.json.gz
    - name: download
      source: https://rest.uniprot.org/locations/stream?compressed=true&fields=id%2Cname%2Ccategory%2Cgene_ontologies%2Cpart_of%2Cis_a&format=tsv&query=%28%2A%29
      destination: targetEngine-inputs/uniprot_locations.tsv.gz
    - name: download
      source: https://raw.githubusercontent.com/opentargets/target_engine/main/src/data_flow/phenotypeScores/20230825_mousePheScores.csv
      destination: targetEngine-inputs/mouse_pheno_scores.csv
