---
config:

  output_path: ./output
  gcp_credentials_path: ./credentials/gcs_credentials.json
  gcp_bucket_path: gs://open-targets-pre-data-releases/24.06dev-test
  log_level: DEBUG

  steps:
    go:
      actions:
        - name: download
          from: http://purl.obolibrary.org/obo/go.obo
          to: gene-ontology-inputs/go.obo

    baselineexpression:
      actions:
        - name: download-latest
          from: gs://otar000-evidence_input/BaselineExpression/json
          to: expression-inputs/baseline_expression.json.gz


  # old settings
  # gsutil: /snap/bin/gsutil
  # riot: /usr/share/apache-jena/bin/riot
  # jq: /usr/bin/jq
  # java_vm: -Xms4096m -Xmx8192m

  # disease:
  #   etl:
  #     hpo_phenotypes:
  #       uri: http://purl.obolibrary.org/obo/hp/hpoa/phenotype.hpoa
  #       output_filename: hpo-phenotypes.jsonl
  #       path: ontology-inputs
  #     efo:
  #       uri: https://github.com/EBISPOT/efo/releases/download/<EFO_RELEASE_VERSION>/efo_otar_slim.owl
  #       output_filename: ontology-efo.jsonl
  #       path: ontology-inputs
  #       owl_jq: '.["@graph"][] | select (.["@type"] == ("owl:Class","owl:Restriction") and ."@id" != null)|.subClassOf=([.subClassOf]|flatten|del(.[]|nulls))|.hasExactSynonym=([.hasExactSynonym]|flatten|del(.[]|nulls))|.hasDbXref=([.hasDbXref]|flatten|del(.[]|nulls))|.inSubset=([.inSubset]|flatten|del(.[]|nulls))|.hasAlternativeId=([.hasAlternativeId]|flatten|del(.[]|nulls))|@json'
  #       diseases_static_file: diseases_efo.jsonl
  #       url_prefix_mapping:
  #         EFO: http://www.ebi.ac.uk/efo/
  #         OTAR: http://www.ebi.ac.uk/efo/
  #         Orphanet: http://www.orpha.net/ORDO/
  #       url_prefix_mapping_default: http://purl.obolibrary.org/obo/
  #     hpo:
  #       uri: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2021-10-10/hp.owl
  #       output_filename: ontology-hpo.jsonl
  #       path: ontology-inputs
  #       owl_jq: '.["@graph"][] | select (.["@type"] == "owl:Class") | @json'
  #     mondo:
  #       uri: https://github.com/monarch-initiative/mondo/releases/download/v2021-12-30/mondo.owl
  #       output_filename: ontology-mondo.jsonl
  #       path: ontology-inputs
  #       owl_jq: '.["@graph"][] | @json'
  #     miniset: yes
  # drug:
  #   http_downloads:
  #     - uri: https://go.drugbank.com/releases/5-1-9/downloads/all-drugbank-vocabulary
  #       path: chembl-inputs
  #       output_filename: drugbank_vocabulary.csv
  #   gs_downloads_latest:
  #     - bucket: otar001-core/DrugBank/annotation
  #       output_filename: drugbank.csv.gz
  #       path: chembl-inputs
  #   etl:
  #     chembl:
  #       type: elasticsearch
  #       url: https://www.ebi.ac.uk/chembl/elk/es
  #       path: chembl-inputs
  #       indices:
  #         chembl-indication:
  #           name: chembl_<CHEMBL_RELEASE_VERSION>_drug_indication
  #           fields:
  #             - _metadata
  #             - molecule_chembl_id
  #             - efo_id
  #             - max_phase_for_ind
  #             - indication_refs
  #         chembl-mechanism:
  #           name: chembl_<CHEMBL_RELEASE_VERSION>_mechanism
  #           fields:
  #             - molecule_chembl_id
  #             - target_chembl_id
  #             - action_type
  #             - mechanism_of_action
  #             - mechanism_refs
  #             - record_id
  #             - parent_molecule_chembl_id
  #             - _metadata
  #         chembl-molecule:
  #           name: chembl_<CHEMBL_RELEASE_VERSION>_molecule
  #           fields:
  #             - molecule_chembl_id
  #             - molecule_hierarchy
  #             - molecule_type
  #             - pref_name
  #             - first_approval
  #             - max_phase
  #             - withdrawn_flag
  #             - black_box_warning
  #             - molecule_synonyms
  #             - cross_references
  #             - chebi_par_id
  #             - molecule_structures
  #         chembl-target:
  #           name: chembl_<CHEMBL_RELEASE_VERSION>_target
  #           fields:
  #             - _metadata
  #             - target_chembl_id
  #             - target_components
  #             - target_type
  #             - pref_name
  #         chembl-drug-warning:
  #           name: chembl_<CHEMBL_RELEASE_VERSION>_drug_warning
  #           fields:
  #             - _metadata
  #             - molecule_chembl_id
  #             - parent_molecule_chembl_id
  #             - efo_id
  #             - efo_term
  #             - efo_id_for_warning_class
  #             - warning_class
  #             - warning_country
  #             - warning_description
  #             - warning_id
  #             - warning_refs
  #             - warning_type
  #             - warning_year
  #   miniset: yes
  # evidence:
  #   gs_downloads_latest:
  #     - bucket: otar000-evidence_input/CancerBiomarkers/json
  #       output_filename: cancerbiomarkers.json.gz
  #       output_spark_dir: cancerbiomarkers
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/Orphanet/json
  #       output_filename: orphanet.json.gz
  #       output_spark_dir: orphanet
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/ClinGen/json
  #       output_filename: clingen.json.gz
  #       output_spark_dir: clingen
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/CRISPR/json
  #       output_filename: crispr.json.gz
  #       output_spark_dir: crispr
  #       path: evidence-files
  #     - bucket: otar006-reactome
  #       output_filename: reactome.json.gz
  #       output_spark_dir: reactome
  #       path: evidence-files
  #     - bucket: otar007-cosmic
  #       output_filename: cosmic.json.gz
  #       output_spark_dir: cosmic
  #       excludes: hallmarks
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/ChEMBL/json
  #       output_filename: chembl.json.gz
  #       output_spark_dir: chembl
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/Genetics_portal/json/
  #       output_filename: genetics-portal-evidences.json.gz
  #       output_spark_dir: genetics-portal-evidences
  #       path: evidence-files
  #     - bucket: otar010-atlas
  #       output_filename: atlas.json.bz2
  #       output_spark_dir: atlas
  #       path: evidence-files
  #     - bucket: otar011-uniprot
  #       output_filename: uniprot.json.gz
  #       output_spark_dir: uniprot
  #       path: evidence-files
  #     - bucket: otar012-eva/disease-target-evidence
  #       output_filename: eva.json.gz
  #       output_spark_dir: eva
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/Gene2Phenotype/json
  #       output_filename: gene2phenotype.json.gz
  #       output_spark_dir: gene2phenotype
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/GenomicsEngland/json
  #       output_filename: genomics_england.json.gz
  #       output_spark_dir: genomics-england
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/IntOgen/json
  #       output_filename: intogen.json.gz
  #       output_spark_dir: intogen
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/IMPC/json
  #       output_filename: impc.json.gz
  #       output_spark_dir: impc
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/Crispr_screens/json
  #       output_filename: crispr_screen.json.gz
  #       output_spark_dir: crispr_screen
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/PROGENy/json
  #       output_filename: progeny.json.gz
  #       output_spark_dir: progeny
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/SLAPEnrich/json
  #       output_filename: slapenrich.json.gz
  #       output_spark_dir: slapenrich
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/SysBio/json
  #       output_filename: sysbio.json.gz
  #       output_spark_dir: sysbio
  #       path: evidence-files
  #     - bucket: otar000-evidence_input/GeneBurden/json
  #       output_filename: gene_burden.json.gz
  #       output_spark_dir: gene_burden
  #       path: evidence-files
  # expression:
  #   http_downloads:
  #     - uri: https://raw.githubusercontent.com/opentargets/expression_hierarchy/master/process/curation.tsv
  #       output_filename: expression_hierarchy_curation.tsv
  #       path: expression-inputs
  #   gs_downloads_latest:
  #     - bucket: atlas_baseline_expression/baseline_expression_binned
  #       output_filename: baseline_expression_binned.tsv
  #       path: expression-inputs
  #     - bucket: atlas_baseline_expression/baseline_expression_counts
  #       output_filename: baseline_expression_counts.tsv
  #       path: expression-inputs
  #     - bucket: atlas_baseline_expression/baseline_expression_zscore_binned
  #       output_filename: baseline_expression_zscore_binned.tsv
  #       path: expression-inputs
  #   etl:
  #     tissue_translation_map:
  #       uri: https://raw.githubusercontent.com/opentargets/expression_hierarchy/master/process/map_with_efos.json
  #       output_filename: tissue-translation-map.json
  #       path: expression-inputs
  #     normal_tissues:
  #       uri: https://www.proteinatlas.org/download/normal_tissue.tsv.zip
  #       output_filename: normal_tissue.tsv.gz
  #       path: expression-inputs
  # homologues:
  #   uri: https://ftp.ensembl.org/pub/release-{release}/json/
  #   path_gene_dictionary: gene_dictionary
  #   uri_homologues: https://ftp.ensembl.org/pub/release-{release}/tsv/ensembl-compara/homologies
  #   path_homologues: homologies
  #   types_homologues:
  #     - protein
  #     - ncrna
  #   path: target-inputs/homologue
  #   release: <ENSEMBL_RELEASE_VERSION>
  #   jq: '.genes[] | [.id, .name] | @tsv'
  #   resources:
  #     - caenorhabditis_elegans
  #     - canis_lupus_familiaris
  #     - cavia_porcellus
  #     - danio_rerio
  #     - drosophila_melanogaster
  #     - macaca_mulatta
  #     - mus_musculus
  #     - oryctolagus_cuniculus
  #     - pan_troglodytes
  #     - rattus_norvegicus
  #     - sus_scrofa
  #     - xenopus_tropicalis
  #     - homo_sapiens
  # interactions:
  #   gs_downloads_latest:
  #     - bucket: otar001-core/stringInteractions
  #       output_filename: string-interactions.txt.gz
  #       path: interactions-inputs
  #   ftp_downloads:
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/ensembl.tsv
  #       output_filename: rna_central_ensembl.tsv
  #       path: interactions-inputs
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping.dat.gz
  #       output_filename: HUMAN_9606_idmapping.dat.gz
  #       path: interactions-inputs
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/intact/various/ot_graphdb/current/data/interactor_pair_interactions.json
  #       output_filename: intact-interactors.json
  #       path: interactions-inputs
  #   http_downloads:
  #     - uri: https://ftp.ensembl.org/pub/release-<ENSEMBL_RELEASE_VERSION>/gtf/homo_sapiens/Homo_sapiens.GRCh38.<ENSEMBL_RELEASE_VERSION>.chr.gtf.gz
  #       output_filename: Homo_sapiens.GRCh38.chr.gtf.gz
  #       path: interactions-inputs
  # mousephenotypes:
  #   gs_downloads_latest:
  #     - bucket: otar001-core/MousePhenotypes
  #       output_filename: mouse_phenotypes.json.gz
  #       path: mouse-phenotypes-inputs
  # pharmacogenomics:
  #   gs_downloads_latest:
  #     - bucket: otar012-eva/pharmacogenomics
  #       output_filename: pharmacogenomics.json.gz
  #       path: pharmacogenomics-inputs
  # pppevidence:
  #   gs_downloads_latest:
  #     - bucket: otar013-ppp/validation_lab/
  #       output_filename: validation_lab.json.gz
  #       path: evidence-files
  #     - bucket: otar013-ppp/encore/
  #       output_filename: encore.json.gz
  #       path: evidence-files
  #     - bucket: otar013-ppp/ot_crispr/
  #       output_filename: ot_crispr.json.gz
  #       path: evidence-files
  # openfda:
  #   http_downloads:
  #     - uri: https://raw.githubusercontent.com/opentargets/platform-etl-backend/master/src/main/resources/blacklisted_events.txt
  #       path: fda-inputs
  #       output_filename: blacklisted_events.txt
  #   etl:
  #     downloads:
  #       uri: https://api.fda.gov/download.json
  #       path: fda-inputs
  #       output_filename: openfda_file_listing.json
  # reactome:
  #   http_downloads:
  #     - uri: https://reactome.org/download/current/ReactomePathways.txt
  #       output_filename: ReactomePathways.txt
  #       path: reactome-inputs
  #     - uri: https://reactome.org/download/current/ReactomePathwaysRelation.txt
  #       output_filename: ReactomePathwaysRelation.txt
  #       path: reactome-inputs
  # so:
  #   etl:
  #     uri: https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/Ontology_Files/so.owl
  #     output_filename: ontology-so-{suffix}.json
  #     path: so-inputs
  #     owl_jq: '.["@graph"][] | select (.["@type"] == "owl:Class" and .id != null)|.subClassOf=([.subClassOf]|flatten|del(.[]|nulls))|.hasExactSynonym=([.hasExactSynonym]|flatten|del(.[]|nulls))|.hasDbXref=([.hasDbXref]|flatten|del(.[]|nulls))|.inSubset=([.inSubset]|flatten|del(.[]|nulls))|.hasAlternativeId=([.hasAlternativeId]|flatten|del(.[]|nulls))|@json'
  # target:
  #   http_downloads:
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/genenames/new/json/hgnc_complete_set.json
  #       output_filename: hgnc_complete_set.json
  #       path: target-inputs/genenames
  #     - uri: https://reactome.org/download/current/Ensembl2Reactome.txt
  #       output_filename: Ensembl2Reactome.txt
  #       path: target-inputs/reactome
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/genenames/hcop/human_all_hcop_sixteen_column.txt.gz
  #       output_filename: human_all_hcop_sixteen_column.txt.gz
  #       path: target-inputs/genenames
  #     - uri: https://cog.sanger.ac.uk/cmp/download/gene_identifiers_latest.csv.gz
  #       output_filename: gene_identifiers_latest.csv.gz
  #       path: target-inputs/project-scores
  #     - uri: https://rest.uniprot.org/uniprotkb/stream?compressed=true&format=txt&query=%28%28reviewed%3Atrue%29%29%20AND%20%28model_organism%3A9606%29
  #       output_filename: uniprot.txt.gz
  #       path: target-inputs/uniprot
  #     - uri: https://rest.uniprot.org/locations/stream?compressed=true&fields=id%2Cname%2Ccategory&format=tsv&query=%28%2A%29
  #       output_filename: uniprot-ssl.tsv.gz
  #       path: target-inputs/uniprot
  #   gs_downloads_latest:
  #     - bucket: otar000-evidence_input/Essentiality/json
  #       output_filename: essentiality.json.gz
  #       path: target-inputs/gene-essentiality
  #     - bucket: otar001-core/subcellularLocations
  #       output_filename: subcellular_locations_ssl.tsv
  #       path: target-inputs/hpa
  #     - bucket: otar007-cosmic
  #       output_filename: cosmic-hallmarks.tsv.gz
  #       path: target-inputs/hallmarks
  #       includes: hallmarks
  #     - bucket: otar001-core/TEPs
  #       output_filename: tep.json.gz
  #       path: target-inputs/tep
  #     - bucket: otar001-core/ChemicalProbes/annotation
  #       output_filename: chemicalprobes.json.gz
  #       path: target-inputs/chemicalprobes
  #     - bucket: otar001-core/TargetSafety/json
  #       output_filename: safetyLiabilities.json.gz
  #       path: target-inputs/safety
  #     - bucket: otar001-core/Tractability
  #       output_filename: tractability.tsv
  #       path: target-inputs/tractability
  #   ftp_downloads:
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_40/gencode.v40.annotation.gff3.gz
  #       output_filename: gencode.gff3.gz
  #       path: target-inputs/gencode
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/id_mapping/database_mappings/ensembl.tsv
  #       output_filename: ensembl.tsv
  #       path: target-inputs/go
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gaf.gz
  #       output_filename: goa_human.gaf.gz
  #       path: target-inputs/go
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_rna.gaf.gz
  #       output_filename: goa_human_rna.gaf.gz
  #       path: target-inputs/go
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gpa.gz
  #       output_filename: goa_human_eco.gpa.gz
  #       path: target-inputs/go
  #     - uri: https://ftp.ensembl.org/pub/release-<ENSEMBL_RELEASE_VERSION>/species_EnsemblVertebrates.txt
  #       output_filename: species_EnsemblVertebrates.txt
  #       path: target-inputs/homologue
  #     - uri: https://ftp.ncbi.nlm.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz
  #       output_filename: Homo_sapiens.gene_info.gz
  #       path: target-inputs/ncbi
  #   etl:
  #     gnomad:
  #       uri: https://storage.googleapis.com/gcp-public-data--gnomad/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz
  #       output_filename: gnomad_lof_by_gene.txt.gz
  #       path: target-inputs/gnomad
  #     subcellular_location:
  #       uri: https://www.proteinatlas.org/download/subcellular_location.tsv.zip
  #       output_filename: subcellular_location.tsv.gz
  #       path: target-inputs/hpa
  #     project_scores:
  #       uri: https://cog.sanger.ac.uk/cmp/download/essentiality_matrices.zip
  #       output_filename: essentiality_matrices.zip
  #       path: target-inputs/project-scores
  #     ensembl:
  #       release: <ENSEMBL_RELEASE_VERSION>
  #       uri: https://ftp.ensembl.org/pub/release-{release}/json/homo_sapiens/homo_sapiens.json
  #       output_filename: homo_sapiens.jsonl
  #       path: target-inputs/ensembl
  #       jq: '.genes[] | {id: .id, biotype: .biotype, description: .description, end: .end, start: .start, strand: .strand, chromosome: .seq_region_name, approvedSymbol: .name, transcripts: .transcripts, signalP: .SignalP, uniprot_trembl: ."Uniprot/SPTREMBL", uniprot_swissprot: ."Uniprot/SWISSPROT"}'
  #   miniset: yes
  # literature:
  #   http_downloads:
  #     - uri: https://ftp.ebi.ac.uk/pub/databases/pmc/DOI/PMID_PMCID_DOI.csv.gz
  #       output_filename: PMID_PMCID_DOI.csv.gz
  #       path: literature-inputs
  # otar:
  #   resource: otarproject
  #   gs_output_dir: otar-inputs
  #   sheets:
  #     - id_spreadsheet: 1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs
  #       worksheet_name: MetaData
  #       output_format: csv
  #       output_filename: otar_meta.csv
  #     - id_spreadsheet: 1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs
  #       worksheet_name: Project2Disease
  #       output_format: csv
  #       output_filename: otar_project_to_efo.csv
  # targetengine:
  #   http_downloads:
  #     - uri: https://www.proteinatlas.org/download/proteinatlas.json.gz
  #       output_filename: proteinatlas.json.gz
  #       path: targetEngine-inputs
  #     - uri: https://rest.uniprot.org/locations/stream?compressed=true&fields=id%2Cname%2Ccategory%2Cgene_ontologies%2Cpart_of%2Cis_a&format=tsv&query=%28%2A%29
  #       output_filename: uniprot_locations.tsv.gz
  #       path: targetEngine-inputs
  #     - uri: https://raw.githubusercontent.com/opentargets/target_engine/main/src/data_flow/phenotypeScores/20230825_mousePheScores.csv
  #       output_filename: mouse_pheno_scores.csv
  #       path: targetEngine-inputs
