---
config:
  drug:
    etl:
      chembl:
        type: elasticsearch
        url: https://www.ebi.ac.uk/chembl/elk/es
        path: chembl-inputs
        indices:
          chembl-indication:
            name: chembl_<CHEMBL_RELEASE_VERSION>_drug_indication
            fields:
              - _metadata
              - molecule_chembl_id
              - efo_id
              - max_phase_for_ind
              - indication_refs
          chembl-mechanism:
            name: chembl_<CHEMBL_RELEASE_VERSION>_mechanism
            fields:
              - molecule_chembl_id
              - target_chembl_id
              - action_type
              - mechanism_of_action
              - mechanism_refs
              - record_id
              - parent_molecule_chembl_id
              - _metadata
          chembl-molecule:
            name: chembl_<CHEMBL_RELEASE_VERSION>_molecule
            fields:
              - molecule_chembl_id
              - molecule_hierarchy
              - molecule_type
              - pref_name
              - first_approval
              - max_phase
              - withdrawn_flag
              - black_box_warning
              - molecule_synonyms
              - cross_references
              - chebi_par_id
              - molecule_structures
          chembl-target:
            name: chembl_<CHEMBL_RELEASE_VERSION>_target
            fields:
              - _metadata
              - target_chembl_id
              - target_components
              - target_type
              - pref_name
          chembl-drug-warning:
            name: chembl_<CHEMBL_RELEASE_VERSION>_drug_warning
            fields:
              - _metadata
              - molecule_chembl_id
              - parent_molecule_chembl_id
              - efo_id
              - efo_term
              - efo_id_for_warning_class
              - warning_class
              - warning_country
              - warning_description
              - warning_id
              - warning_refs
              - warning_type
              - warning_year
    miniset: yes
