name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: install pis
        run: uv sync --all-extras --dev

      - name: run tests
        run: uv run pytest

  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: install pis
        run: uv sync --all-extras --dev

      - name: run ruff
        run: uv run ruff check --output-format=github .
